### PR TITLE
feat: add better support for unique columns

### PR DESCRIPTION
**Pull request by WellingtonNico**
Hello again!

I asked you how could I set a column as unique, you told me to use something like this:
```dart
index(ColumnIndex.unique, 'email', ['email']);
```

it didn't work because it generated this sql, which has a syntax error near INDEX(using postgres at least, but I checked in many AI models and both told me it is wrong for mysql too):
```sql
CREATE TABLE IF NOT EXISTS "users" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL,
    "avatar" VARCHAR(250) NULL,
    "password" VARCHAR(200) NOT NULL,
    "email" VARCHAR(60) NOT NULL,
    "phone" VARCHAR(60) NULL,
    "description" TEXT NULL,
    "birthday" DATE NULL,
    "created_at" TIMESTAMP NULL,
    "updated_at" TIMESTAMP NULL,
    unique INDEX "email" ("email")
)
```

so I added an argument for each column type to generate unique columns with unique constraint, I tested for my migration and now it works, see the difference:
before:
```dart
await createTableNotExists('users', () {
      id();
      string('name', length: 100);
      string('avatar', length: 250, nullable: true);
      string('password', length: 200);
      string('email', length: 60);
      string('phone', length: 60, nullable: true);
      text('description', nullable: true);
      date('birthday', nullable: true);
      timeStamps();
      index(ColumnIndex.unique, 'email', ['email']);
});
```
after
```dart
await createTableNotExists('users', () {
      id();
      string('name', length: 100);
      string('avatar', length: 250, nullable: true);
      string('password', length: 200);
      string('email', length: 60,unique: true);
      string('phone', length: 60, nullable: true);
      text('description', nullable: true);
      date('birthday', nullable: true);
      timeStamps();
});
```

it now generates a query like this:
```sql
CREATE TABLE IF NOT EXISTS "users" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL,
    "avatar" VARCHAR(250) NULL,
    "password" VARCHAR(200) NOT NULL,
    "email" VARCHAR(60) NOT NULL UNIQUE,
    "phone" VARCHAR(60) NULL,
    "description" TEXT NULL,
    "birthday" DATE NULL,
    "created_at" TIMESTAMP NULL,
    "updated_at" TIMESTAMP NULL
)
```

happy to help!

### CODE REVIEW

**Comment by WellingtonNico** [comment]
any updates here guys?

**Comment by javad-zobeidi** [comment]
@WellingtonNico What if we have a combination of two columns?

ex:
combination  mobile with email

**Comment by WellingtonNico** [comment]
> @WellingtonNico What if we have a combination of two columns?
> 
> ex: combination mobile with email

I think it's not a commom usage, thats way PRIMARY is made for...

**Comment by javad-zobeidi** [comment]
We must consider all the conditions

**Comment by javad-zobeidi** [comment]
@WellingtonNico 
Thank you for the PR

**Pull request merged**
